#!/usr/bin/env python3
"""Patches the android/ folder generated by `flutter create .`.

Run it once after `flutter create .` (the CI workflow does this):

    python3 tool/patch_android.py

It is idempotent - running it twice changes nothing the second time.

What it does
1. AndroidManifest.xml: adds the camera + Bluetooth permissions and sets the
   app name to "StockBill Pro".
2. android/build.gradle(.kts): forces compileSdk 36 on plugin sub-projects
   (older plugins compile against 33/34 and break the build) (otherwise the build fails with
   "requires libraries ... to compile against version 34 or later").
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ANDROID = os.path.join(ROOT, "android")

PERMISSIONS = """
    <!-- Added by tool/patch_android.py -->
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
    <uses-feature android:name="android.hardware.bluetooth" android:required="false" />
"""

KTS_SNIPPET = """
// Added by tool/patch_android.py: some plugins still compile against an old SDK.
// (Reflection is used so this does not depend on the AGP classes being importable.)
subprojects {
    if (project.name != "app") {
        afterEvaluate {
            val androidExt = project.extensions.findByName("android")
            if (androidExt != null) {
                try {
                    val method = androidExt.javaClass.methods.firstOrNull {
                        it.name == "compileSdkVersion" &&
                            it.parameterTypes.size == 1 &&
                            it.parameterTypes[0] == Int::class.javaPrimitiveType
                    }
                    method?.invoke(androidExt, 36)
                } catch (e: Exception) {
                    println("compileSdk override skipped for " + project.name + ": " + e.message)
                }
            }
        }
    }
}
"""

GROOVY_SNIPPET = """
// Added by tool/patch_android.py: some plugins still compile against an old SDK.
subprojects {
    if (project.name != "app") {
        afterEvaluate { p ->
            if (p.hasProperty("android")) {
                p.android.compileSdkVersion 36
            }
        }
    }
}
"""


def patch_manifest():
    path = os.path.join(ANDROID, "app", "src", "main", "AndroidManifest.xml")
    if not os.path.exists(path):
        print("AndroidManifest.xml not found - run `flutter create .` first")
        return False
    s = open(path, encoding="utf-8").read()
    if "Added by tool/patch_android.py" not in s:
        m = re.search(r"<manifest[^>]*>", s)
        if not m:
            print("could not find <manifest> tag")
            return False
        s = s[: m.end()] + PERMISSIONS + s[m.end():]
    s = re.sub(r'android:label="[^"]*"', 'android:label="StockBill Pro"', s, count=1)
    open(path, "w", encoding="utf-8").write(s)
    print("AndroidManifest.xml patched")
    return True


def patch_gradle():
    kts = os.path.join(ANDROID, "build.gradle.kts")
    groovy = os.path.join(ANDROID, "build.gradle")
    if os.path.exists(kts):
        path, snippet = kts, KTS_SNIPPET
    elif os.path.exists(groovy):
        path, snippet = groovy, GROOVY_SNIPPET
    else:
        print("android/build.gradle(.kts) not found")
        return False
    s = open(path, encoding="utf-8").read()
    if "Added by tool/patch_android.py" in s:
        print(os.path.basename(path), "already patched")
        return True
    # Must be registered BEFORE `project.evaluationDependsOn(":app")`.
    idx = s.find("evaluationDependsOn")
    if idx != -1:
        block_start = s.rfind("subprojects", 0, idx)
        s = s[:block_start] + snippet.lstrip("\n") + "\n" + s[block_start:]
    else:
        s = s + "\n" + snippet
    open(path, "w", encoding="utf-8").write(s)
    print(os.path.basename(path), "patched")
    return True


if __name__ == "__main__":
    ok = patch_manifest()
    ok = patch_gradle() and ok
    sys.exit(0 if ok else 1)
